import numpy as np
m=np.array([88,88,102,111,101,94,104,81,86,77,86,107,104,106,112,105],float)
d=np.array([79,79, 77, 75, 74,81, 82,84,75,76,88, 78, 74, 74, 78, 79],float)
e=m-d; C=95.0
print("受试者B  n=%d"%len(m))
print("设备(ECG真值): mean=%.2f std=%.2f range=[%.0f,%.0f]"%(d.mean(),d.std(ddof=1),d.min(),d.max()))
print("模型         : mean=%.2f std=%.2f range=[%.0f,%.0f]"%(m.mean(),m.std(ddof=1),m.min(),m.max()))
print()
print("逐点误差:", ", ".join("%+d"%x for x in e))
print("Bias = %+.2f | MAE = %.2f | RMSE = %.2f | 误差std = %.2f"
      %(e.mean(),np.abs(e).mean(),np.sqrt((e**2).mean()),e.std(ddof=1)))
print("误差为正(偏高)占比 = %.0f%%   ±5bpm命中率 = %.0f%%"%(100*(e>0).mean(),100*(np.abs(e)<=5).mean()))
print()
print("="*56)
print("【判别性检验】这次真值远离带中心, 可以判决了")
print("="*56)
print("搜索带[50,140]中心 C = %.1f"%C)
print("真值均值 T           = %.2f"%d.mean())
print("|T - C|              = %.2f bpm  (受试者A只有2.83 -> 无法判别)"%abs(d.mean()-C))
print("判别门槛 2σ/√n       = %.2f bpm"%(2*m.std(ddof=1)/np.sqrt(len(m))))
print("-> %s"%("【可判别】" if abs(d.mean()-C)>2*m.std(ddof=1)/np.sqrt(len(m)) else "不可判别"))
print()
print("假设1 '模型准'        预测模型均值≈ %.1f , 实测 %.1f , 差 %+.1f"%(d.mean(),m.mean(),m.mean()-d.mean()))
print("假设2 '回归带中心'    预测模型均值≈ %.1f , 实测 %.1f , 差 %+.1f"%(C,m.mean(),m.mean()-C))
print()
lam=(m.mean()-d.mean())/(C-d.mean())
print("把模型输出拟合为  m = (1-λ)·真值 + λ·带中心")
print("  λ = %.2f   -> 输出中约 %.0f%% 来自带中心, 仅 %.0f%% 跟随真值"%(lam,100*lam,100*(1-lam)))
