print("="*76)
print("发现: 我的离线分析用错了数据源")
print("="*76)
print("落盘(capture_*.npz):")
print("  frames     = input_sequence_tchw  <- frame_buffer_for_model (生产缓冲区)")
print("               固定 SEQUENCE_LENGTH=160 帧, 不做重采样")
print("  timestamps = self.frame_buffer_timestamps  <- 生产缓冲区时间戳")
print()
print("影子链路(实际驱动/max显示)实际喂给模型的是:")
print("  frame_buffer_shadow -> resample_recent_window_production()")
print("  -> 取最近10秒真实帧, 插值成 T_out=301 帧")
print()
print("两者是【不同的缓冲区、不同的帧数、不同的时间窗】:")
print("  生产缓冲区: 160帧, 无重采样, 覆盖时长随帧率漂移(实测12s~370s)")
print("  影子缓冲区: 301帧, 有重采样, 严格覆盖最近10.0秒")
print()
print("="*76)
print("这解释了 离线83.8 vs 线上93.9 的10bpm差异")
print("="*76)
print("我此前所有'离线重放'实际上重放的是【生产链路的输入】,")
print("而 /max 显示的是【影子链路的输出】。两条链路输入不同源。")
print()
print("=> 我之前得出的 '离线MAE 4.22' '门控有效' 等结论,")
print("   建立在错误的数据源上, 不能直接迁移到影子链路。")
print()
print("=> 也意味着: 到目前为止, 影子链路真正喂给模型的帧")
print("   【从未被落盘、从未被我直接检验过】。")
print()
print("下一步必须做的: 在影子链路里落盘它自己的输入(301帧+原始窗口帧),")
print("才能真正对照。否则继续分析生产缓冲区是南辕北辙。")
