print("="*76)
print("更正: 我上一条只对了一半")
print("="*76)
print("核实脚本后:")
print("  s6 (得出主峰60.5/83.8): 直接喂160帧原始序列, 用真实fps算谱")
print("     -> 确实【没有】走影子链路的重采样, 这部分我说对了")
print()
print("  s9/s11(得出MAE 6.92 / 4.22 / argmax 83.8): 代码里明确有")
print("     tw/fw 取最近10秒 -> interp1d 插值 -> 301帧 -> permute -> 推理")
print("     -> 这【完整复现了】影子链路的重采样流程, 我说'全部用错数据源'是错的")
print()
print("="*76)
print("那么真正剩下的差异是什么?")
print("="*76)
print("s9/s11 与线上的唯一实质差异:")
print("  数据来源仍是 capture_*.npz, 即 frame_buffer_for_model 的160帧快照")
print("  而线上影子用的是 frame_buffer_shadow(独立deque, 按时间裁剪)")
print()
print("代码显示两个缓冲区在同一处 append 同一个 face_roi_processed_tensor,")
print("所以【帧内容同源】。差异只在:")
print("  1. 生产缓冲maxlen=160(固定帧数); 影子按 2*WINDOW_SEC 时间裁剪")
print("  2. 落盘时刻 = 生产推理时刻(需160帧满); 影子每轮循环都算")
print("  3. 时间戳: 生产用 frame_buffer_timestamps; 影子用独立的 _shadow_now_ts")
print("     两者在同一次循环中先后调用 time.time(), 差异极小")
print()
print("=> 帧内容同源, 重采样流程已复现, 但结果差10bpm。")
print("   差异必在【窗口内实际包含哪些帧】上, 即缓冲区裁剪策略。")
print()
print("这仍需实测, 不能再推断。下一步: 在影子链路加只读落盘。")
