import numpy as np
print("="*70)
print("为什么我上一轮会看错? 复盘")
print("="*70)
print("上一轮我只比较了两者的【均值】:")
print("   argmax 均值 81.8 (偏差+3.5)   tracker 均值 70.4 (偏差-7.9)")
print("   -> 我据此宣称 argmax 更准。这是【均值抵消陷阱】。")
print()
print("本轮逐样本配对后真相:")
print("   argmax  MAE=20.03  std=21.82   <- 大幅正负误差相互抵消, 均值才显得好")
print("   tracker MAE= 6.92  std= 6.31")
print()
print("argmax误差分位 p10=-21.0 p50=+2.2 p90=+32.5  <- 摆动巨大")
print("tracker误差分位p10=-13.3 p50=-5.4 p90= +2.0  <- 集中")
print()
print("均值接近真值 ≠ 准确。这正是我在受试者A那轮已经踩过的同一个坑,")
print("我又踩了第二次(A轮是'带中心巧合', 本轮是'正负抵消')。")
print()
print("="*70)
print("配对t检验解读(我上一条脚本的判定文字也写错了)")
print("="*70)
print("d = |tracker误差| - |argmax误差| = -13.11 bpm,  t = -9.26")
print("t为负且|t|=9.26 >> 2  -> tracker【显著更优】")
print("我脚本里的判定条件写成 t>2 才算显著, 忽略了负号方向,")
print("于是打印出'差异不显著'。这是脚本bug, 正确结论是 tracker 显著更优。")
print()
print("逐样本胜负 tracker 45胜 : argmax 3胜 : 平手18  -> 压倒性")
print("±10bpm命中率 tracker 77% vs argmax 20%")
print("MAE 95%CI 完全不重叠: tracker[5.72,8.23] vs argmax[17.36,22.59]")
